import Head from "next/head";
import Image from "next/image";
import React, { useContext } from "react";
import styles from "../styles/Home.module.css";

import { graphCmsRequest} from "../lib/services";

import { UserContext } from "../components/card/Layout";
import Herro from "../components/card/Herro";
import {picturesQuery, categoriesQuery } from "../lib/graphql";
import Galery from "../components/card/Images";
import PostDetails from "../components/card/ImagesHome";


export default function Home({ myPictures,myCategories}) {
  const { smallMenu, setSmallMenu } = useContext(UserContext);
  const myPicturesNew = myPictures.images123
  const myCategoriesNew = myCategories.newCategories

  let mx = myCategoriesNew.map(x=>{
    let obj ={}
    let z = x.title
    let m = myPicturesNew.filter(y=>y.newCategory.title==z)
    

    obj["catTitle"] = z
    obj["description"] = x.description
    obj["image"] = m
    return obj
  
  })

 console.log(mx)

  return (
    <div className={""}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main onClick= {() => setSmallMenu(false)} className={styles.main }>

      <div className="h-screen sm:h-96 bg-green-50 relative m-4 z-10 w-screen">
              <Herro/>
      </div>
       
        <div className="flex flex-col items-center justify-center">
           
        <div className="mt-2 text-center">
             {mx.map(j=>(
              <div className="space-y-6 mb-10" key={j.id}>
                <h2 className="font-bold font-lg text-xl lg:text-4xl">{j.catTitle}</h2>
                <p className="italic">{j.description}</p>
               
                <div>
                     < PostDetails myGalery={j.image}  />
                </div>
            
              
              </div>
              
             ))}
         
         
           {/* <Galery myGalery={myPicturesNew} /> */}
        </div>
      
       
        </div>
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="font-bold text-2xl text-green-900 mx-2">BALIJAVA DIGITAL</span>
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  // const posts = await getProducts("http://localhost:4000/products");
  const myPictures = await graphCmsRequest(picturesQuery);
  const myCategories = await graphCmsRequest(categoriesQuery);
  return {
    props: {
      // posts,
      myPictures: myPictures,
      myCategories:myCategories
    },
  };
}

